//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICE.POS.Test.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.PosServicesSoap")]
    public interface PosServicesSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestConnection", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool TestConnection();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetCashierPwd", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SetCashierPwd(string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCashierList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetCashierList(string branchNo, string cashierId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBranchInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetBranchInfo(string branchNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBranchList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetBranchList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBranchStock", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetBranchStock(string branchNo, string branchText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBarcodeList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetBarcodeList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetItemList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetItemList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetItemClsList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetItemClsList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPosStatusList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetPosStatusList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBaseCodeType", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetBaseCodeType();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBaseCodeInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetBaseCodeInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPaymentInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetPaymentInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFunction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetFunction(string branchNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPMSheetMaster", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetPMSheetMaster(string transNO, string sheetNO, string branchNO, string status, System.DateTime startDate, System.DateTime endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPMSheetDetail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ICE.POS.Test.ServiceReference1.t_pm_sheet_master GetPMSheetDetail(string sheetNO, ref System.Data.DataTable dt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdatePosStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int UpdatePosStatus(ICE.POS.Test.ServiceReference1.t_sys_pos_status posStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertCardPayList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int InsertCardPayList(t_rm_card_paylist[] cardPayList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InPayFlowList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool InPayFlowList(t_rm_payflow[] payFlow);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InPMSheetMaster", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string InPMSheetMaster(ICE.POS.Test.ServiceReference1.t_pm_sheet_master _sheetMaster);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPosSet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetPosSet();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class t_pm_sheet_master : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sheet_noField;
        
        private string trans_noField;
        
        private string db_noField;
        
        private string branch_noField;
        
        private string d_branch_noField;
        
        private string voucher_noField;
        
        private string supcust_noField;
        
        private string coin_noField;
        
        private string pay_wayField;
        
        private System.Nullable<System.DateTime> pay_dateField;
        
        private string dept_flagField;
        
        private string approve_flagField;
        
        private System.DateTime oper_dateField;
        
        private System.Nullable<System.DateTime> work_dateField;
        
        private System.Nullable<System.DateTime> valid_dateField;
        
        private System.Nullable<decimal> order_amtField;
        
        private string order_statusField;
        
        private string order_manField;
        
        private string oper_idField;
        
        private string confirm_manField;
        
        private string dept_idField;
        
        private string sale_wayField;
        
        private string reverse_flagField;
        
        private string reverse_sheetField;
        
        private string direct_flagField;
        
        private string trans_flagField;
        
        private string acct_flagField;
        
        private string other1Field;
        
        private string other2Field;
        
        private string other3Field;
        
        private System.Nullable<decimal> sheet_amtField;
        
        private string branch_flagField;
        
        private string com_flagField;
        
        private System.Nullable<decimal> num1Field;
        
        private System.Nullable<decimal> num2Field;
        
        private string relate_sheet_noField;
        
        private string memoField;
        
        private t_pm_sheet_detail[] detailListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string sheet_no {
            get {
                return this.sheet_noField;
            }
            set {
                this.sheet_noField = value;
                this.RaisePropertyChanged("sheet_no");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string trans_no {
            get {
                return this.trans_noField;
            }
            set {
                this.trans_noField = value;
                this.RaisePropertyChanged("trans_no");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string db_no {
            get {
                return this.db_noField;
            }
            set {
                this.db_noField = value;
                this.RaisePropertyChanged("db_no");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string branch_no {
            get {
                return this.branch_noField;
            }
            set {
                this.branch_noField = value;
                this.RaisePropertyChanged("branch_no");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string d_branch_no {
            get {
                return this.d_branch_noField;
            }
            set {
                this.d_branch_noField = value;
                this.RaisePropertyChanged("d_branch_no");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string voucher_no {
            get {
                return this.voucher_noField;
            }
            set {
                this.voucher_noField = value;
                this.RaisePropertyChanged("voucher_no");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string supcust_no {
            get {
                return this.supcust_noField;
            }
            set {
                this.supcust_noField = value;
                this.RaisePropertyChanged("supcust_no");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string coin_no {
            get {
                return this.coin_noField;
            }
            set {
                this.coin_noField = value;
                this.RaisePropertyChanged("coin_no");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string pay_way {
            get {
                return this.pay_wayField;
            }
            set {
                this.pay_wayField = value;
                this.RaisePropertyChanged("pay_way");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<System.DateTime> pay_date {
            get {
                return this.pay_dateField;
            }
            set {
                this.pay_dateField = value;
                this.RaisePropertyChanged("pay_date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string dept_flag {
            get {
                return this.dept_flagField;
            }
            set {
                this.dept_flagField = value;
                this.RaisePropertyChanged("dept_flag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string approve_flag {
            get {
                return this.approve_flagField;
            }
            set {
                this.approve_flagField = value;
                this.RaisePropertyChanged("approve_flag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public System.DateTime oper_date {
            get {
                return this.oper_dateField;
            }
            set {
                this.oper_dateField = value;
                this.RaisePropertyChanged("oper_date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<System.DateTime> work_date {
            get {
                return this.work_dateField;
            }
            set {
                this.work_dateField = value;
                this.RaisePropertyChanged("work_date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public System.Nullable<System.DateTime> valid_date {
            get {
                return this.valid_dateField;
            }
            set {
                this.valid_dateField = value;
                this.RaisePropertyChanged("valid_date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public System.Nullable<decimal> order_amt {
            get {
                return this.order_amtField;
            }
            set {
                this.order_amtField = value;
                this.RaisePropertyChanged("order_amt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string order_status {
            get {
                return this.order_statusField;
            }
            set {
                this.order_statusField = value;
                this.RaisePropertyChanged("order_status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string order_man {
            get {
                return this.order_manField;
            }
            set {
                this.order_manField = value;
                this.RaisePropertyChanged("order_man");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string oper_id {
            get {
                return this.oper_idField;
            }
            set {
                this.oper_idField = value;
                this.RaisePropertyChanged("oper_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string confirm_man {
            get {
                return this.confirm_manField;
            }
            set {
                this.confirm_manField = value;
                this.RaisePropertyChanged("confirm_man");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string dept_id {
            get {
                return this.dept_idField;
            }
            set {
                this.dept_idField = value;
                this.RaisePropertyChanged("dept_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string sale_way {
            get {
                return this.sale_wayField;
            }
            set {
                this.sale_wayField = value;
                this.RaisePropertyChanged("sale_way");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string reverse_flag {
            get {
                return this.reverse_flagField;
            }
            set {
                this.reverse_flagField = value;
                this.RaisePropertyChanged("reverse_flag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string reverse_sheet {
            get {
                return this.reverse_sheetField;
            }
            set {
                this.reverse_sheetField = value;
                this.RaisePropertyChanged("reverse_sheet");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string direct_flag {
            get {
                return this.direct_flagField;
            }
            set {
                this.direct_flagField = value;
                this.RaisePropertyChanged("direct_flag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string trans_flag {
            get {
                return this.trans_flagField;
            }
            set {
                this.trans_flagField = value;
                this.RaisePropertyChanged("trans_flag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string acct_flag {
            get {
                return this.acct_flagField;
            }
            set {
                this.acct_flagField = value;
                this.RaisePropertyChanged("acct_flag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string other1 {
            get {
                return this.other1Field;
            }
            set {
                this.other1Field = value;
                this.RaisePropertyChanged("other1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string other2 {
            get {
                return this.other2Field;
            }
            set {
                this.other2Field = value;
                this.RaisePropertyChanged("other2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string other3 {
            get {
                return this.other3Field;
            }
            set {
                this.other3Field = value;
                this.RaisePropertyChanged("other3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=30)]
        public System.Nullable<decimal> sheet_amt {
            get {
                return this.sheet_amtField;
            }
            set {
                this.sheet_amtField = value;
                this.RaisePropertyChanged("sheet_amt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string branch_flag {
            get {
                return this.branch_flagField;
            }
            set {
                this.branch_flagField = value;
                this.RaisePropertyChanged("branch_flag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string com_flag {
            get {
                return this.com_flagField;
            }
            set {
                this.com_flagField = value;
                this.RaisePropertyChanged("com_flag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=33)]
        public System.Nullable<decimal> num1 {
            get {
                return this.num1Field;
            }
            set {
                this.num1Field = value;
                this.RaisePropertyChanged("num1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=34)]
        public System.Nullable<decimal> num2 {
            get {
                return this.num2Field;
            }
            set {
                this.num2Field = value;
                this.RaisePropertyChanged("num2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public string relate_sheet_no {
            get {
                return this.relate_sheet_noField;
            }
            set {
                this.relate_sheet_noField = value;
                this.RaisePropertyChanged("relate_sheet_no");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public string memo {
            get {
                return this.memoField;
            }
            set {
                this.memoField = value;
                this.RaisePropertyChanged("memo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=37)]
        public t_pm_sheet_detail[] detailList {
            get {
                return this.detailListField;
            }
            set {
                this.detailListField = value;
                this.RaisePropertyChanged("detailList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class t_pm_sheet_detail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal flow_idField;
        
        private string sheet_noField;
        
        private string item_noField;
        
        private System.Nullable<decimal> order_qtyField;
        
        private System.Nullable<decimal> real_qtyField;
        
        private System.Nullable<decimal> large_qtyField;
        
        private System.Nullable<decimal> orgi_priceField;
        
        private System.Nullable<decimal> valid_priceField;
        
        private System.Nullable<decimal> sub_amtField;
        
        private System.Nullable<decimal> taxField;
        
        private System.Nullable<System.DateTime> valid_dateField;
        
        private string other1Field;
        
        private string other2Field;
        
        private string other3Field;
        
        private System.Nullable<decimal> num1Field;
        
        private System.Nullable<decimal> num2Field;
        
        private System.Nullable<decimal> num3Field;
        
        private System.Nullable<decimal> route_qtyField;
        
        private System.Nullable<decimal> jhd_qtyField;
        
        private string sheet_moField;
        
        private System.Nullable<decimal> mo_qtyField;
        
        private string sheet_poField;
        
        private System.Nullable<decimal> po_qtyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal flow_id {
            get {
                return this.flow_idField;
            }
            set {
                this.flow_idField = value;
                this.RaisePropertyChanged("flow_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string sheet_no {
            get {
                return this.sheet_noField;
            }
            set {
                this.sheet_noField = value;
                this.RaisePropertyChanged("sheet_no");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string item_no {
            get {
                return this.item_noField;
            }
            set {
                this.item_noField = value;
                this.RaisePropertyChanged("item_no");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<decimal> order_qty {
            get {
                return this.order_qtyField;
            }
            set {
                this.order_qtyField = value;
                this.RaisePropertyChanged("order_qty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<decimal> real_qty {
            get {
                return this.real_qtyField;
            }
            set {
                this.real_qtyField = value;
                this.RaisePropertyChanged("real_qty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<decimal> large_qty {
            get {
                return this.large_qtyField;
            }
            set {
                this.large_qtyField = value;
                this.RaisePropertyChanged("large_qty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<decimal> orgi_price {
            get {
                return this.orgi_priceField;
            }
            set {
                this.orgi_priceField = value;
                this.RaisePropertyChanged("orgi_price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<decimal> valid_price {
            get {
                return this.valid_priceField;
            }
            set {
                this.valid_priceField = value;
                this.RaisePropertyChanged("valid_price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<decimal> sub_amt {
            get {
                return this.sub_amtField;
            }
            set {
                this.sub_amtField = value;
                this.RaisePropertyChanged("sub_amt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<decimal> tax {
            get {
                return this.taxField;
            }
            set {
                this.taxField = value;
                this.RaisePropertyChanged("tax");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public System.Nullable<System.DateTime> valid_date {
            get {
                return this.valid_dateField;
            }
            set {
                this.valid_dateField = value;
                this.RaisePropertyChanged("valid_date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string other1 {
            get {
                return this.other1Field;
            }
            set {
                this.other1Field = value;
                this.RaisePropertyChanged("other1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string other2 {
            get {
                return this.other2Field;
            }
            set {
                this.other2Field = value;
                this.RaisePropertyChanged("other2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string other3 {
            get {
                return this.other3Field;
            }
            set {
                this.other3Field = value;
                this.RaisePropertyChanged("other3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public System.Nullable<decimal> num1 {
            get {
                return this.num1Field;
            }
            set {
                this.num1Field = value;
                this.RaisePropertyChanged("num1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public System.Nullable<decimal> num2 {
            get {
                return this.num2Field;
            }
            set {
                this.num2Field = value;
                this.RaisePropertyChanged("num2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public System.Nullable<decimal> num3 {
            get {
                return this.num3Field;
            }
            set {
                this.num3Field = value;
                this.RaisePropertyChanged("num3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public System.Nullable<decimal> route_qty {
            get {
                return this.route_qtyField;
            }
            set {
                this.route_qtyField = value;
                this.RaisePropertyChanged("route_qty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public System.Nullable<decimal> jhd_qty {
            get {
                return this.jhd_qtyField;
            }
            set {
                this.jhd_qtyField = value;
                this.RaisePropertyChanged("jhd_qty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string sheet_mo {
            get {
                return this.sheet_moField;
            }
            set {
                this.sheet_moField = value;
                this.RaisePropertyChanged("sheet_mo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=20)]
        public System.Nullable<decimal> mo_qty {
            get {
                return this.mo_qtyField;
            }
            set {
                this.mo_qtyField = value;
                this.RaisePropertyChanged("mo_qty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string sheet_po {
            get {
                return this.sheet_poField;
            }
            set {
                this.sheet_poField = value;
                this.RaisePropertyChanged("sheet_po");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=22)]
        public System.Nullable<decimal> po_qty {
            get {
                return this.po_qtyField;
            }
            set {
                this.po_qtyField = value;
                this.RaisePropertyChanged("po_qty");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class t_rm_saleflow : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal com_noField;
        
        private decimal flow_idField;
        
        private string flow_noField;
        
        private string branch_noField;
        
        private string item_noField;
        
        private System.Nullable<decimal> source_priceField;
        
        private System.Nullable<decimal> sale_priceField;
        
        private System.Nullable<decimal> sale_qntyField;
        
        private System.Nullable<decimal> sale_moneyField;
        
        private string sell_wayField;
        
        private string oper_idField;
        
        private string sale_manField;
        
        private string counter_noField;
        
        private System.DateTime oper_dateField;
        
        private string remote_flagField;
        
        private string shift_noField;
        
        private string com_flagField;
        
        private string spec_flagField;
        
        private System.Nullable<decimal> pref_amtField;
        
        private System.Nullable<decimal> in_priceField;
        
        private System.Nullable<decimal> n_stanField;
        
        private string chr_stanField;
        
        private string posidField;
        
        private System.DateTime uptimeField;
        
        private string is_jxcField;
        
        private System.DateTime real_dateField;
        
        private string spec_sheet_noField;
        
        private string spec_group_idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal com_no {
            get {
                return this.com_noField;
            }
            set {
                this.com_noField = value;
                this.RaisePropertyChanged("com_no");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal flow_id {
            get {
                return this.flow_idField;
            }
            set {
                this.flow_idField = value;
                this.RaisePropertyChanged("flow_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string flow_no {
            get {
                return this.flow_noField;
            }
            set {
                this.flow_noField = value;
                this.RaisePropertyChanged("flow_no");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string branch_no {
            get {
                return this.branch_noField;
            }
            set {
                this.branch_noField = value;
                this.RaisePropertyChanged("branch_no");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string item_no {
            get {
                return this.item_noField;
            }
            set {
                this.item_noField = value;
                this.RaisePropertyChanged("item_no");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<decimal> source_price {
            get {
                return this.source_priceField;
            }
            set {
                this.source_priceField = value;
                this.RaisePropertyChanged("source_price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<decimal> sale_price {
            get {
                return this.sale_priceField;
            }
            set {
                this.sale_priceField = value;
                this.RaisePropertyChanged("sale_price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<decimal> sale_qnty {
            get {
                return this.sale_qntyField;
            }
            set {
                this.sale_qntyField = value;
                this.RaisePropertyChanged("sale_qnty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<decimal> sale_money {
            get {
                return this.sale_moneyField;
            }
            set {
                this.sale_moneyField = value;
                this.RaisePropertyChanged("sale_money");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string sell_way {
            get {
                return this.sell_wayField;
            }
            set {
                this.sell_wayField = value;
                this.RaisePropertyChanged("sell_way");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string oper_id {
            get {
                return this.oper_idField;
            }
            set {
                this.oper_idField = value;
                this.RaisePropertyChanged("oper_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string sale_man {
            get {
                return this.sale_manField;
            }
            set {
                this.sale_manField = value;
                this.RaisePropertyChanged("sale_man");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string counter_no {
            get {
                return this.counter_noField;
            }
            set {
                this.counter_noField = value;
                this.RaisePropertyChanged("counter_no");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public System.DateTime oper_date {
            get {
                return this.oper_dateField;
            }
            set {
                this.oper_dateField = value;
                this.RaisePropertyChanged("oper_date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string remote_flag {
            get {
                return this.remote_flagField;
            }
            set {
                this.remote_flagField = value;
                this.RaisePropertyChanged("remote_flag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string shift_no {
            get {
                return this.shift_noField;
            }
            set {
                this.shift_noField = value;
                this.RaisePropertyChanged("shift_no");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string com_flag {
            get {
                return this.com_flagField;
            }
            set {
                this.com_flagField = value;
                this.RaisePropertyChanged("com_flag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string spec_flag {
            get {
                return this.spec_flagField;
            }
            set {
                this.spec_flagField = value;
                this.RaisePropertyChanged("spec_flag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public System.Nullable<decimal> pref_amt {
            get {
                return this.pref_amtField;
            }
            set {
                this.pref_amtField = value;
                this.RaisePropertyChanged("pref_amt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
        public System.Nullable<decimal> in_price {
            get {
                return this.in_priceField;
            }
            set {
                this.in_priceField = value;
                this.RaisePropertyChanged("in_price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=20)]
        public System.Nullable<decimal> n_stan {
            get {
                return this.n_stanField;
            }
            set {
                this.n_stanField = value;
                this.RaisePropertyChanged("n_stan");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string chr_stan {
            get {
                return this.chr_stanField;
            }
            set {
                this.chr_stanField = value;
                this.RaisePropertyChanged("chr_stan");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string posid {
            get {
                return this.posidField;
            }
            set {
                this.posidField = value;
                this.RaisePropertyChanged("posid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public System.DateTime uptime {
            get {
                return this.uptimeField;
            }
            set {
                this.uptimeField = value;
                this.RaisePropertyChanged("uptime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string is_jxc {
            get {
                return this.is_jxcField;
            }
            set {
                this.is_jxcField = value;
                this.RaisePropertyChanged("is_jxc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public System.DateTime real_date {
            get {
                return this.real_dateField;
            }
            set {
                this.real_dateField = value;
                this.RaisePropertyChanged("real_date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string spec_sheet_no {
            get {
                return this.spec_sheet_noField;
            }
            set {
                this.spec_sheet_noField = value;
                this.RaisePropertyChanged("spec_sheet_no");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string spec_group_id {
            get {
                return this.spec_group_idField;
            }
            set {
                this.spec_group_idField = value;
                this.RaisePropertyChanged("spec_group_id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class t_rm_payflow : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal com_noField;
        
        private decimal flow_idField;
        
        private string flow_noField;
        
        private System.Nullable<decimal> sale_amountField;
        
        private string branch_noField;
        
        private string pay_wayField;
        
        private string sell_wayField;
        
        private string card_noField;
        
        private string vip_noField;
        
        private string coin_noField;
        
        private System.Nullable<decimal> coin_rateField;
        
        private System.Nullable<decimal> pay_amountField;
        
        private System.DateTime oper_dateField;
        
        private string oper_idField;
        
        private string counter_noField;
        
        private string sale_manField;
        
        private string memoField;
        
        private string voucher_noField;
        
        private string remote_flagField;
        
        private string exchange_flagField;
        
        private string shift_noField;
        
        private string com_flagField;
        
        private string posidField;
        
        private System.Nullable<System.DateTime> uptimeField;
        
        private string is_jxcField;
        
        private System.Nullable<System.DateTime> real_dateField;
        
        private t_rm_saleflow[] saleFlowlListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal com_no {
            get {
                return this.com_noField;
            }
            set {
                this.com_noField = value;
                this.RaisePropertyChanged("com_no");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal flow_id {
            get {
                return this.flow_idField;
            }
            set {
                this.flow_idField = value;
                this.RaisePropertyChanged("flow_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string flow_no {
            get {
                return this.flow_noField;
            }
            set {
                this.flow_noField = value;
                this.RaisePropertyChanged("flow_no");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<decimal> sale_amount {
            get {
                return this.sale_amountField;
            }
            set {
                this.sale_amountField = value;
                this.RaisePropertyChanged("sale_amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string branch_no {
            get {
                return this.branch_noField;
            }
            set {
                this.branch_noField = value;
                this.RaisePropertyChanged("branch_no");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string pay_way {
            get {
                return this.pay_wayField;
            }
            set {
                this.pay_wayField = value;
                this.RaisePropertyChanged("pay_way");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string sell_way {
            get {
                return this.sell_wayField;
            }
            set {
                this.sell_wayField = value;
                this.RaisePropertyChanged("sell_way");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string card_no {
            get {
                return this.card_noField;
            }
            set {
                this.card_noField = value;
                this.RaisePropertyChanged("card_no");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string vip_no {
            get {
                return this.vip_noField;
            }
            set {
                this.vip_noField = value;
                this.RaisePropertyChanged("vip_no");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string coin_no {
            get {
                return this.coin_noField;
            }
            set {
                this.coin_noField = value;
                this.RaisePropertyChanged("coin_no");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public System.Nullable<decimal> coin_rate {
            get {
                return this.coin_rateField;
            }
            set {
                this.coin_rateField = value;
                this.RaisePropertyChanged("coin_rate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<decimal> pay_amount {
            get {
                return this.pay_amountField;
            }
            set {
                this.pay_amountField = value;
                this.RaisePropertyChanged("pay_amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public System.DateTime oper_date {
            get {
                return this.oper_dateField;
            }
            set {
                this.oper_dateField = value;
                this.RaisePropertyChanged("oper_date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string oper_id {
            get {
                return this.oper_idField;
            }
            set {
                this.oper_idField = value;
                this.RaisePropertyChanged("oper_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string counter_no {
            get {
                return this.counter_noField;
            }
            set {
                this.counter_noField = value;
                this.RaisePropertyChanged("counter_no");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string sale_man {
            get {
                return this.sale_manField;
            }
            set {
                this.sale_manField = value;
                this.RaisePropertyChanged("sale_man");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string memo {
            get {
                return this.memoField;
            }
            set {
                this.memoField = value;
                this.RaisePropertyChanged("memo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string voucher_no {
            get {
                return this.voucher_noField;
            }
            set {
                this.voucher_noField = value;
                this.RaisePropertyChanged("voucher_no");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string remote_flag {
            get {
                return this.remote_flagField;
            }
            set {
                this.remote_flagField = value;
                this.RaisePropertyChanged("remote_flag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string exchange_flag {
            get {
                return this.exchange_flagField;
            }
            set {
                this.exchange_flagField = value;
                this.RaisePropertyChanged("exchange_flag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string shift_no {
            get {
                return this.shift_noField;
            }
            set {
                this.shift_noField = value;
                this.RaisePropertyChanged("shift_no");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string com_flag {
            get {
                return this.com_flagField;
            }
            set {
                this.com_flagField = value;
                this.RaisePropertyChanged("com_flag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string posid {
            get {
                return this.posidField;
            }
            set {
                this.posidField = value;
                this.RaisePropertyChanged("posid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=23)]
        public System.Nullable<System.DateTime> uptime {
            get {
                return this.uptimeField;
            }
            set {
                this.uptimeField = value;
                this.RaisePropertyChanged("uptime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string is_jxc {
            get {
                return this.is_jxcField;
            }
            set {
                this.is_jxcField = value;
                this.RaisePropertyChanged("is_jxc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=25)]
        public System.Nullable<System.DateTime> real_date {
            get {
                return this.real_dateField;
            }
            set {
                this.real_dateField = value;
                this.RaisePropertyChanged("real_date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=26)]
        public t_rm_saleflow[] saleFlowlList {
            get {
                return this.saleFlowlListField;
            }
            set {
                this.saleFlowlListField = value;
                this.RaisePropertyChanged("saleFlowlList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class t_rm_card_paylist : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal idField;
        
        private string flow_noField;
        
        private string card_typeField;
        
        private string card_idField;
        
        private System.Nullable<decimal> amountField;
        
        private System.DateTime pay_timeField;
        
        private string other1Field;
        
        private string other2Field;
        
        private string branch_noField;
        
        private System.Nullable<decimal> residual_amtField;
        
        private string com_flagField;
        
        private System.Nullable<decimal> vip_accField;
        
        private System.Nullable<System.DateTime> real_dateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string flow_no {
            get {
                return this.flow_noField;
            }
            set {
                this.flow_noField = value;
                this.RaisePropertyChanged("flow_no");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string card_type {
            get {
                return this.card_typeField;
            }
            set {
                this.card_typeField = value;
                this.RaisePropertyChanged("card_type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string card_id {
            get {
                return this.card_idField;
            }
            set {
                this.card_idField = value;
                this.RaisePropertyChanged("card_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<decimal> amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.DateTime pay_time {
            get {
                return this.pay_timeField;
            }
            set {
                this.pay_timeField = value;
                this.RaisePropertyChanged("pay_time");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string other1 {
            get {
                return this.other1Field;
            }
            set {
                this.other1Field = value;
                this.RaisePropertyChanged("other1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string other2 {
            get {
                return this.other2Field;
            }
            set {
                this.other2Field = value;
                this.RaisePropertyChanged("other2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string branch_no {
            get {
                return this.branch_noField;
            }
            set {
                this.branch_noField = value;
                this.RaisePropertyChanged("branch_no");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<decimal> residual_amt {
            get {
                return this.residual_amtField;
            }
            set {
                this.residual_amtField = value;
                this.RaisePropertyChanged("residual_amt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string com_flag {
            get {
                return this.com_flagField;
            }
            set {
                this.com_flagField = value;
                this.RaisePropertyChanged("com_flag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<decimal> vip_acc {
            get {
                return this.vip_accField;
            }
            set {
                this.vip_accField = value;
                this.RaisePropertyChanged("vip_acc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<System.DateTime> real_date {
            get {
                return this.real_dateField;
            }
            set {
                this.real_dateField = value;
                this.RaisePropertyChanged("real_date");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class t_sys_pos_status : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string branch_noField;
        
        private string posidField;
        
        private string posdescField;
        
        private string hostipField;
        
        private string hostnameField;
        
        private string operdateField;
        
        private System.Nullable<decimal> amountField;
        
        private decimal orderqtyField;
        
        private System.DateTime lasttimeField;
        
        private string lastcashierField;
        
        private string statusField;
        
        private string otherField;
        
        private string com_flagField;
        
        private string load_flagField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string branch_no {
            get {
                return this.branch_noField;
            }
            set {
                this.branch_noField = value;
                this.RaisePropertyChanged("branch_no");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string posid {
            get {
                return this.posidField;
            }
            set {
                this.posidField = value;
                this.RaisePropertyChanged("posid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string posdesc {
            get {
                return this.posdescField;
            }
            set {
                this.posdescField = value;
                this.RaisePropertyChanged("posdesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string hostip {
            get {
                return this.hostipField;
            }
            set {
                this.hostipField = value;
                this.RaisePropertyChanged("hostip");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string hostname {
            get {
                return this.hostnameField;
            }
            set {
                this.hostnameField = value;
                this.RaisePropertyChanged("hostname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string operdate {
            get {
                return this.operdateField;
            }
            set {
                this.operdateField = value;
                this.RaisePropertyChanged("operdate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<decimal> amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public decimal orderqty {
            get {
                return this.orderqtyField;
            }
            set {
                this.orderqtyField = value;
                this.RaisePropertyChanged("orderqty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public System.DateTime lasttime {
            get {
                return this.lasttimeField;
            }
            set {
                this.lasttimeField = value;
                this.RaisePropertyChanged("lasttime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string lastcashier {
            get {
                return this.lastcashierField;
            }
            set {
                this.lastcashierField = value;
                this.RaisePropertyChanged("lastcashier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string other {
            get {
                return this.otherField;
            }
            set {
                this.otherField = value;
                this.RaisePropertyChanged("other");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string com_flag {
            get {
                return this.com_flagField;
            }
            set {
                this.com_flagField = value;
                this.RaisePropertyChanged("com_flag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string load_flag {
            get {
                return this.load_flagField;
            }
            set {
                this.load_flagField = value;
                this.RaisePropertyChanged("load_flag");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PosServicesSoapChannel : ICE.POS.Test.ServiceReference1.PosServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PosServicesSoapClient : System.ServiceModel.ClientBase<ICE.POS.Test.ServiceReference1.PosServicesSoap>, ICE.POS.Test.ServiceReference1.PosServicesSoap {
        
        public PosServicesSoapClient() {
        }
        
        public PosServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PosServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PosServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PosServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public bool TestConnection() {
            return base.Channel.TestConnection();
        }
        
        public string SetCashierPwd(string pwd) {
            return base.Channel.SetCashierPwd(pwd);
        }
        
        public System.Data.DataSet GetCashierList(string branchNo, string cashierId) {
            return base.Channel.GetCashierList(branchNo, cashierId);
        }
        
        public System.Data.DataSet GetBranchInfo(string branchNo) {
            return base.Channel.GetBranchInfo(branchNo);
        }
        
        public System.Data.DataSet GetBranchList() {
            return base.Channel.GetBranchList();
        }
        
        public System.Data.DataSet GetBranchStock(string branchNo, string branchText) {
            return base.Channel.GetBranchStock(branchNo, branchText);
        }
        
        public System.Data.DataSet GetBarcodeList() {
            return base.Channel.GetBarcodeList();
        }
        
        public System.Data.DataSet GetItemList() {
            return base.Channel.GetItemList();
        }
        
        public System.Data.DataSet GetItemClsList() {
            return base.Channel.GetItemClsList();
        }
        
        public System.Data.DataSet GetPosStatusList() {
            return base.Channel.GetPosStatusList();
        }
        
        public System.Data.DataSet GetBaseCodeType() {
            return base.Channel.GetBaseCodeType();
        }
        
        public System.Data.DataSet GetBaseCodeInfo() {
            return base.Channel.GetBaseCodeInfo();
        }
        
        public System.Data.DataSet GetPaymentInfo() {
            return base.Channel.GetPaymentInfo();
        }
        
        public System.Data.DataSet GetFunction(string branchNo) {
            return base.Channel.GetFunction(branchNo);
        }
        
        public System.Data.DataSet GetPMSheetMaster(string transNO, string sheetNO, string branchNO, string status, System.DateTime startDate, System.DateTime endDate) {
            return base.Channel.GetPMSheetMaster(transNO, sheetNO, branchNO, status, startDate, endDate);
        }
        
        public ICE.POS.Test.ServiceReference1.t_pm_sheet_master GetPMSheetDetail(string sheetNO, ref System.Data.DataTable dt) {
            return base.Channel.GetPMSheetDetail(sheetNO, ref dt);
        }
        
        public int UpdatePosStatus(ICE.POS.Test.ServiceReference1.t_sys_pos_status posStatus) {
            return base.Channel.UpdatePosStatus(posStatus);
        }
        
        public int InsertCardPayList(t_rm_card_paylist[] cardPayList) {
            return base.Channel.InsertCardPayList(cardPayList);
        }
        
        public bool InPayFlowList(t_rm_payflow[] payFlow) {
            return base.Channel.InPayFlowList(payFlow);
        }
        
        public string InPMSheetMaster(ICE.POS.Test.ServiceReference1.t_pm_sheet_master _sheetMaster) {
            return base.Channel.InPMSheetMaster(_sheetMaster);
        }
        
        public string GetPosSet() {
            return base.Channel.GetPosSet();
        }
    }
}
